### ISSUE TITLE
organizations support?

### ISSUE THREAD

**Issue by juanjovazquez** [coreos/dex#185] opened 2015-11-19 12:43 UTC
In the process of evaluation of IAM solutions for an SaaS application, we're assessing if dex could be an option (maybe in the long term). However, it'd be mandatory for us to be able to manage different organizations or tenants in order to set specific policies for them. It'd be something similar as the concept of Organizations in [Github's security model](https://github.com/blog/674-introducing-organizations). Is dex intended to support, now or in the future, this kind of multi-tenant scenarios?.

I'm not an expert in OpenId Connect but I suppose that this would have to do more with Authz than with Auth.

Thanks in advance.

**Comment by bobbyrullo** [comment] 2015-11-19 19:04
Hi @juanjovazquez - We are almost definitely going the route of adding some notion of groups to dex (see #175). There's a bit of trickiness involved in the way groups interact with clients/RPs (clients in the OAuth2 sense) eg, what clients have visibility to what groups. And we're also exploring whether or not we can make this interact with OIDC in a nice way (are group memberships in the Identity JWT's claims? What if they belong to 1000 groups? )

We need this stuff for our various authz purposes as well, so stay tuned: keep an eye on #175.

**Comment by bobbyrullo** [comment] 2015-11-19 19:04
closing this as a dupe of #175

**Closed by bobbyrullo** 2015-11-19 19:04 UTC
Labels: reviewed/duplicate
