### ISSUE TITLE
nil pointer panic in overlord

### ISSUE THREAD

**Issue by colhom** [coreos/dex#217] opened 2015-12-16 20:26 UTC
I'm seeing a panic when key-secrets is empty. (I did this by mistake). This is happening with the latest docker image:

repo=quay.io/coreos/dex
tag=031fef508db2

Possibly related to #130 
Here's the stack trace

```
INFO: Performed 0 db migrations
INFO: Binding to 0.0.0.0:5557...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4b837b]

goroutine 8 [running]:
github.com/coreos/go-oidc/key.(*PrivateKeyRotator).nextRotation(0xc20806a800, 0x0, 0x0, 0x0)
	/go/src/github.com/coreos/dex/Godeps/_workspace/src/github.com/coreos/go-oidc/key/rotate.go:80 +0x28b
github.com/coreos/go-oidc/key.func·002()
	/go/src/github.com/coreos/dex/Godeps/_workspace/src/github.com/coreos/go-oidc/key/rotate.go:117 +0x6c
created by github.com/coreos/go-oidc/key.(*PrivateKeyRotator).Run
	/go/src/github.com/coreos/dex/Godeps/_workspace/src/github.com/coreos/go-oidc/key/rotate.go:133 +0x19c

goroutine 1 [chan receive]:
main.main()
	/go/src/github.com/coreos/dex/Godeps/_workspace/src/github.com/coreos/dex/cmd/dex-overlord/main.go:147 +0x1740

goroutine 5 [chan receive]:
database/sql.(*DB).connectionOpener(0xc20806cdc0)
	/usr/src/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/usr/src/go/src/database/sql/sql.go:452 +0x31c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 6 [IO wait]:
net.(*pollDesc).Wait(0xc2080d4df0, 0x72, 0x0, 0x0)
	/usr/src/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080d4df0, 0x0, 0x0)
	/usr/src/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080d4d90, 0x0, 0x7fd89e724ef0, 0xc2080a2418)
	/usr/src/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208032118, 0x479e34, 0x0, 0x0)
	/usr/src/go/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc208032118, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc2080524e0, 0x7fd89e727b10, 0xc208032118, 0x0, 0x0)
	/usr/src/go/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc2080524e0, 0x0, 0x0)
	/usr/src/go/src/net/http/server.go:1718 +0x154
main.func·001()
	/go/src/github.com/coreos/dex/Godeps/_workspace/src/github.com/coreos/dex/cmd/dex-overlord/main.go:143 +0x2a
created by main.main
	/go/src/github.com/coreos/dex/Godeps/_workspace/src/github.com/coreos/dex/cmd/dex-overlord/main.go:144 +0x16e9

goroutine 7 [select]:
github.com/coreos/dex/db.func·002()
	/go/src/github.com/coreos/dex/Godeps/_workspace/src/github.com/coreos/dex/db/gc.go:59 +0x3db
created by github.com/coreos/dex/db.(*GarbageCollector).Run
	/go/src/github.com/coreos/dex/Godeps/_workspace/src/github.com/coreos/dex/db/gc.go:78 +0xfb

```

**Comment by ericchiang** [comment] 2015-12-16 20:54
Code causing the panic in `github.com/coreos/go-oidc/key` is [here](https://github.com/coreos/dex/blob/bf13c3bc37aca48f027bf960a4361a8059d975ae/Godeps/_workspace/src/github.com/coreos/go-oidc/key/rotate.go#L68-L80) (last line).

Yes, this this is being caused by providing no key-secrets. We're creating a pointer to return but never assigning to it [here](https://github.com/coreos/dex/blob/master/db/key.go#L168-L197) within dex's `db` package.

This bug will be prevented by checking for no key secrets in #215, but it would be good to check again within the scope of that db function.

**Comment by bobbyrullo** [comment] 2015-12-17 01:46
"low hanging fruit" - so confident!

**Closed** 2015-12-17 17:24 UTC
Labels: kind/friction, low hanging fruit, priority/P1
