### ISSUE TITLE
kubectl refresh issues

### ISSUE THREAD

**Issue by zihaoyu** [coreos/dex#828] opened 2017-03-01 15:16 UTC
We use `dex` as OIDC provider for `kube-apiserver`, and configure `kubeconfig` to use [OIDC authenticator](https://kubernetes.io/docs/admin/authentication/#option-1---oidc-authenticator) in user config. Our expiration settings look like the following:
```
expiry:
  signingKeys: 6h
  idTokens: 24h
```
However we noticed that when we come into office the next day, `kubectl` can't authenticate us some times:
```
error: You must be logged in to the server (the server has asked for the client to provide credentials)
```

So we need to get new tokens and put them in `kubeconfig` file.

Is it because `signingKeys` were rotated before `idTokens` were re-issued, so `dex` didn't know how to decrypt the tokens?

**Comment by ericchiang** [comment] 2017-03-01 17:08
@zihaoyu we've been seeing this issue crop up recently.

Dex's logic will keep old signing keys around as long as there are id tokens that it could have signed. There will no longer be used to sign, but will be kept around to verify. I don't think this is the source of the issue, but yes, we've seen this response from kubectl a bit lately.

What version of dex are you using? What logins (LDAP, GitHub, etc.)?

Anecdotally we've seen these bugs reported less with our recent release v2.2.3. Could you try that?

**Comment by zihaoyu** [comment] 2017-03-01 17:10
@ericchiang We use GitHub connector, and `quay.io/coreos/dex:v2.0.0-beta.1` image. Will try v2.2.3. Thanks.

**Comment by joshrosso** [comment] 2017-03-01 18:25
Experiencing an identical behavior with:

Dex: 2.1.0
Connector: LDAP

**Comment by ericchiang** [comment] 2017-03-01 19:09
I think I can see an issue https://github.com/coreos/dex/blob/3797a71ec9b5cbd254908f9d509a9dd21d0cfb96/server/rotation.go#L135

**Comment by ericchiang** [comment] 2017-03-01 19:38
Yep, the expiry bug is causing verification keys to arbitrarily be deleted. I think this is causing the issue. Will send a fix ASAP.

**Comment by ericchiang** [comment] 2017-03-01 21:16
Okay I was finally able to reproduce this

```
$ kubectl get pods
I0301 13:16:35.917132    1893 logs.go:41] RoundTripper returned a response & error; ignoring response
Unable to connect to the server: No valid id-token, and cannot refresh without refresh-token
```

**Comment by joshrosso** [comment] 2017-03-01 21:21
Thanks @ericchiang.

So #829 fixes the above message?

**Comment by ericchiang** [comment] 2017-03-01 21:24
@joshrosso From my testing, yes it looks like https://github.com/coreos/dex/pull/829 fixes the issue. Observed behavior of v2.2.3 is: after two rotations the validation key is prematurely marked as expired (after ~12 hours by default). During this time the ID Token hasn't expired, so kubectl doesn't trigger a refresh, but the public key is no longer returned by dex, so the API server marks it as invalid.

Going to do a v2.2.4 release with https://github.com/coreos/dex/pull/829 cc @rithujohn191

**Comment by joshrosso** [comment] 2017-03-01 21:27
Thanks. We're happy to validate this once the `v2.2.4` drops.

**Comment by zihaoyu** [comment] 2017-03-01 21:27
Same here. Thanks for the fast turnaround!

**Comment by ericchiang** [comment] 2017-03-01 21:29
v2.2.4 is out. Let me know if you can login in 12 hours :)

**Comment by joshrosso** [comment] 2017-03-01 22:21
In flight, will let you know tomorrow.

**Comment by zihaoyu** [comment] 2017-03-02 13:38
@ericchiang This morning, some of us reported successful `kubectl` operations without needing to update tokens manually. However some saw another error:
```
Unable to connect to the server: could not refresh token: server_error
```
Looking at `dex` logs:
```
2017-03-02T13:36:50.906120876Z time="2017-03-02T13:36:50Z" level=error msg="failed to refresh identity: no upstream access token found" 
```
Any ideas?

**Comment by zihaoyu** [comment] 2017-03-02 16:25
@ericchiang Before the bump

**Comment by zihaoyu** [comment] 2017-03-07 02:19
@ericchiang `v2.2.4` seems to be working fine. After a weekend we didn't have to get new tokens manually.

**Closed** 2017-03-07 17:56 UTC
Labels: kind/bug, priority/P0

**Comment by InAnimaTe** [comment] 2017-03-22 19:45
For anyone running Tectonic and running into this, 1.5.2-tectonic.1 is running 2.1.0 of Dex which means you are affected. Looks like 1.5.3 release [upgrades](https://coreos.com/tectonic/releases/) Dex to 2.2.4 in which case things should work. 

Thanks to everyone for fixing this!
