### ISSUE TITLE
Getting Started error. Any advice?

### ISSUE THREAD

**Issue by AlexandreRoba** [coreos/dex#797] opened 2017-02-05 19:16 UTC
Hi all,

I have followed the "Get started" document and ran the server:
```Bash
✔ ~/projects/dex/src/github.com/coreos/dex [master|✔] 
19:58 $ ./bin/dex serve examples/config-dev.yaml
time="2017-02-05T19:00:19Z" level=info msg="config issuer: http://127.0.0.1:5556/dex" 
time="2017-02-05T19:00:19Z" level=info msg="config connector: mock" 
time="2017-02-05T19:00:19Z" level=info msg="config connector: local passwords enabled" 
time="2017-02-05T19:00:19Z" level=info msg="config storage: sqlite3" 
time="2017-02-05T19:00:19Z" level=info msg="config static client: example-app" 
time="2017-02-05T19:00:19Z" level=info msg="keys expired, rotating" 
time="2017-02-05T19:00:20Z" level=info msg="keys rotated, next rotation: 2017-02-06 01:00:20.149057794 +0000 UTC" 
time="2017-02-05T19:00:20Z" level=info msg="listening (http) on 0.0.0.0:5556" 
```

I then run the example-app:
```Bash
✘-2 ~/projects/dex/src/github.com/coreos/dex [master|✔] 
20:02 $ ./bin/example-app --debug
2017/02/05 20:02:42 GET /dex/.well-known/openid-configuration HTTP/1.1
Host: 127.0.0.1:5556

Error: Failed to query provider "http://127.0.0.1:5556/dex": Get http://127.0.0.1:5556/dex/.well-known/openid-configuration: EOF
Usage:
  example-app [flags]

Flags:
      --client-id string        OAuth2 client ID of this application. (default "example-app")
      --client-secret string    OAuth2 client secret of this application. (default "ZXhhbXBsZS1hcHAtc2VjcmV0")
      --debug                   Print all request and responses from the OpenID Connect issuer.
      --issuer string           URL of the OpenID Connect issuer. (default "http://127.0.0.1:5556/dex")
      --issuer-root-ca string   Root certificate authorities for the issuer. Defaults to host certs.
      --listen string           HTTP(S) address to listen at. (default "http://127.0.0.1:5555")
      --redirect-uri string     Callback URL for OAuth2 responses. (default "http://127.0.0.1:5555/callback")
      --tls-cert string         X509 cert file to present when serving HTTPS.
      --tls-key string          Private key for the HTTPS cert.

error: Failed to query provider "http://127.0.0.1:5556/dex": Get http://127.0.0.1:5556/dex/.well-known/openid-configuration: EOF
```

When I try to access the URL http://127.0.0.1:5556/dex/.well-known/openid-configuration
I'm getting a timeout. 

Any idea at what I should start looking at?

**Comment by ericchiang** [comment] 2017-02-06 03:21
```
time="2017-02-05T19:00:20Z" level=info msg="listening (http) on 0.0.0.0:5556" 
```

Is that not causing you to listen on 127.0.0.1:5556? Maybe try setting the IP directly?

**Comment by AlexandreRoba** [comment] 2017-02-06 07:47
Hi, thanks for the quick reply.
I don't think it is coming from the IP configuration for couple of reason.
1) I'm not getting a network error. I'm getting a time out. I tried to telnet the endpoint and I'm getting an answer. When the service is stoped I'm then getting an error
2) The endpoint that the test app is trying to reach is a discovery endoint. Would it make sense to filter on the host there? Not sure...
I'm going to try to debug it and find out were it is coming from... But as I'm a nooby in GO it my take me some time :)
Regards,
Alex.

**Comment by ericchiang** [comment] 2017-02-15 16:34
Since there's not really enough info for us to go off of here I'm going to close this for now. @AlexandreRoba if you have any new info, please feel free to commend and I can reopen.

**Closed by ericchiang** 2017-02-15 16:34 UTC

**Comment by euforic** [comment] 2017-09-11 21:09
@AlexandreRoba if you are running on a mac the odds are its a port issue. try switching the first number of all the ports from 5 to 9 so `9555` `9556` and instead of using `0.0.0.0` use `127.0.0.1`

I think the problem is when the ip is set to `0.0.0.0` if fails to bind the ports for `127.0.0.1` but it is able to bind the ports for you local ip address. Not sure why it doesn't still fail though

**Comment by AlexandreRoba** [comment] 2017-09-12 07:24
That was it. Thanks for the help.

**Comment by Jonwei** [comment] 2017-09-28 01:49
@euforic similar problem, and change the IP to 127.0.0.1 and port to 9555, 9556. it still can't work. any advice ?

in my mac ,  run `./bin/dex serve examples/config-dev.yaml`, it always be killed.  terminal  show as below:
 [1]    4190 killed     ./bin/dex serve examples/config-dev.yaml

**Comment by kaman86** [comment] 2019-03-19 19:31
I am able to run ./bin/dex serve examples/config-dev.yaml successfully.

But when I run ./bin/example-app to start the client, I get the following error:

"error: Failed to query provider "https://dex.krishnachoudhary.tk": Get https://dex.krishnachoudhary.tk/.well-known/openid-configuration: x509: certificate is valid for api.internal.krishnacho
udhary.tk, api.krishnachoudhary.tk, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, not dex.krishnachoudhary.tk."

When I change the issuer url to https://api.krishnachoudhary.tk i get the following error:

"error: Failed to query provider "https://dex.krishnachoudhary.tk": Get https://dex.krishnachoudhary.tk/.well-known/openid-configuration: EOF"
