### ISSUE TITLE
Connecting Existing User Database

### ISSUE THREAD

**Issue by Pulankit-so** [coreos/dex#1098] opened 2017-10-11 08:11 UTC
Hi, 
I would like to use dex for a microservice based architecture. I went through the docs and also got the sample app working. Though I am still in doubt if dex would allow me to connect my existing database and authentication logic build on top of it for authenticating the users. if yes, do suggest me how can I achieve the same. Thanks.

**Comment by ericchiang** [comment] 2017-10-11 23:25
Dex doesn't have a way to connect to user databases per say, it connects to other user management systems through protocols like LDAP, SAML, or OAuth2. If your user database implements any of these protocols dex can use it to back user login.

There's been discussion about a more general backing mechanism, but I have some concerns about some of those proposals https://github.com/coreos/dex/issues/1020

Closing since there's not a bug or proposal here.

**Closed by ericchiang** 2017-10-11 23:25 UTC
