### ISSUE TITLE
Refresh token become invalid after the same user requests authorization

### ISSUE THREAD

**Issue by kkohtaka** [coreos/dex#973] opened 2017-06-20 15:49 UTC
It looks a refresh token become invalid after the owner of the token requests to be authorized, even if the request was sent from another machine. Is this a correct behavior?

If this is by design, how can we implement an application which can authorize the same user from multiple machines?

**Repro steps**:

1. Check out the master of the repository and build dex and example-app.
2. Add your static password on ./examples/config-dev.yaml.
3. Run `./cmd/dex/dex serve ./examples/config-dev.yaml`.
4. Run `./cmd/example-app/example-app`.
5. Open http://127.0.0.1:5555 with an browser and...
    5.1. Click "Login" button with "Request offline access" checked.
    5.2. Click "Log in with Email", enter your email and password, and click "Grant Access".
    5.3. Confirm tokens have been received.
6. Open http://127.0.0.1:5555 with another browser and...
    6.1. Log in with the same email and password as used at step 5.
7. Return to the browser (at step 5.3.) and click "Redeem refresh token" to confirm if the refresh token is valid.

**Expected results**:

Fields "Token", "Claims", and "Refresh Token" are updated.

**Actual results**:

The following message is displayed.
```
failed to get token: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_request","error_description":"Refresh token is invalid or has already been claimed by another client."}
```

**Comment by zihaoyu** [comment] 2017-06-22 18:52
I think this is a duplicate of #787 . This is expected and recommended oauth2 security practice. https://tools.ietf.org/html/rfc6819#section-5.2.2.3

> ... in case of such an access attempt the valid refresh token and the access authorization associated with it are both revoked.

**Comment by rithujohn191** [comment] 2017-06-22 23:18
Thank you @zihaoyu . You are right.

Dex intentionally does this per OAuth2 security [recommendations](https://tools.ietf.org/html/rfc6819#section-5.2.2.3). It helps identify when refresh tokens are stolen. Also we limit the number of refresh tokens a user-client pair can posses at a time to 1.

**Closed by rithujohn191** 2017-06-22 23:18 UTC

**Comment by tksm** [comment] 2017-06-23 01:53
@rithujohn191 I really love Dex's security features like [Refresh Token Rotation](https://tools.ietf.org/html/rfc6819#section-5.2.2.3), but in our case this behavior is a bit of a problem.

We use Dex as a iDP for Kubernetes. IIUC, supporting only one refresh token means we cannot use kubectl on multiple machines. Is there a plan or roadmap to support multiple refresh tokens (multiple offline sessions)? Refresh Token Rotation itself is not a problem in our case.

For example Google supports 50 refresh tokens per user account per client.
https://developers.google.com/identity/protocols/OAuth2#expiration

**Comment by ericchiang** [comment] 2017-06-23 02:33
@tksm as stated in #787 we'd be open to making this configurable.

As for kubernetes, you can use a service account for minting kubeconfigs that can be used on multiple machines. We've generally recommended that for those kind of use cases.

**Comment by tksm** [comment] 2017-06-23 05:02
@ericchiang Thank you for your reply. 

Refresh Token Rotation is not a problem in our case, so we don't need to turn off this function.   What do you think about supporting multiple refresh tokens per user per client?

**Comment by pheuter** [comment] 2017-10-11 00:35
We're currently running into an issue where we're using [VSTS](https://docs.microsoft.com/en-us/vsts/build-release/apps/cd/azure/deploy-container-kubernetes) to deploy to a Tectonic Kube Cluster. The first several releases worked fine by now we're starting to see the oauth refresh token error.

I've created a kubeconfig using admin > My Account > Access Management under the impression that it will always be valid unless I explicitly revoke it, but it doesn't seem to be the case. Any guidance greatly appreciated.
